//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdi3_10.Cli_SOAP_CSharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://DESKTOP-PGL18OV:8280/sdi3-10.EJB/TripsService")]
        public string sdi3_10_Cli_SOAP_CSharp_TripsService_EjbTripsServiceService {
            get {
                return ((string)(this["sdi3_10_Cli_SOAP_CSharp_TripsService_EjbTripsServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://DESKTOP-PGL18OV:8280/sdi3-10.EJB/SeatsService")]
        public string sdi3_10_Cli_SOAP_CSharp_SeatsService_EjbSeatsServiceService {
            get {
                return ((string)(this["sdi3_10_Cli_SOAP_CSharp_SeatsService_EjbSeatsServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://DESKTOP-PGL18OV:8280/sdi3-10.EJB/RatingsService")]
        public string sdi3_10_Cli_SOAP_CSharp_RatingsService_EjbRatingsServiceService {
            get {
                return ((string)(this["sdi3_10_Cli_SOAP_CSharp_RatingsService_EjbRatingsServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://DESKTOP-PGL18OV:8280/sdi3-10.EJB/UsersService")]
        public string sdi3_10_Cli_SOAP_CSharp_UsersService_EjbUsersServiceService {
            get {
                return ((string)(this["sdi3_10_Cli_SOAP_CSharp_UsersService_EjbUsersServiceService"]));
            }
        }
    }
}
