//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace sdi3_10.Cli_SOAP_CSharp.TripsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EjbTripsServiceServiceSoapBinding", Namespace="http://impl.business.sdi.com/")]
    public partial class EjbTripsServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback findPromoterOrParticipatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback findByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback findByPromoterAndOpenOperationCompleted;
        
        private System.Threading.SendOrPostCallback registerTripOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAvailableTripsOperationCompleted;
        
        private System.Threading.SendOrPostCallback viajesPendientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback findAllUserTripOperationCompleted;
        
        private System.Threading.SendOrPostCallback findToCloseOperationCompleted;
        
        private System.Threading.SendOrPostCallback findByPromoterOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EjbTripsServiceService() {
            this.Url = global::sdi3_10.Cli_SOAP_CSharp.Properties.Settings.Default.sdi3_10_Cli_SOAP_CSharp_TripsService_EjbTripsServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event findPromoterOrParticipatedCompletedEventHandler findPromoterOrParticipatedCompleted;
        
        /// <remarks/>
        public event findByIdCompletedEventHandler findByIdCompleted;
        
        /// <remarks/>
        public event findByPromoterAndOpenCompletedEventHandler findByPromoterAndOpenCompleted;
        
        /// <remarks/>
        public event registerTripCompletedEventHandler registerTripCompleted;
        
        /// <remarks/>
        public event getAvailableTripsCompletedEventHandler getAvailableTripsCompleted;
        
        /// <remarks/>
        public event viajesPendientesCompletedEventHandler viajesPendientesCompleted;
        
        /// <remarks/>
        public event findAllUserTripCompletedEventHandler findAllUserTripCompleted;
        
        /// <remarks/>
        public event findToCloseCompletedEventHandler findToCloseCompleted;
        
        /// <remarks/>
        public event findByPromoterCompletedEventHandler findByPromoterCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public listadoDTO findPromoterOrParticipated([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
            object[] results = this.Invoke("findPromoterOrParticipated", new object[] {
                        arg0,
                        arg0Specified});
            return ((listadoDTO)(results[0]));
        }
        
        /// <remarks/>
        public void findPromoterOrParticipatedAsync(long arg0, bool arg0Specified) {
            this.findPromoterOrParticipatedAsync(arg0, arg0Specified, null);
        }
        
        /// <remarks/>
        public void findPromoterOrParticipatedAsync(long arg0, bool arg0Specified, object userState) {
            if ((this.findPromoterOrParticipatedOperationCompleted == null)) {
                this.findPromoterOrParticipatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindPromoterOrParticipatedOperationCompleted);
            }
            this.InvokeAsync("findPromoterOrParticipated", new object[] {
                        arg0,
                        arg0Specified}, this.findPromoterOrParticipatedOperationCompleted, userState);
        }
        
        private void OnfindPromoterOrParticipatedOperationCompleted(object arg) {
            if ((this.findPromoterOrParticipatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findPromoterOrParticipatedCompleted(this, new findPromoterOrParticipatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trip findById([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
            object[] results = this.Invoke("findById", new object[] {
                        arg0,
                        arg0Specified});
            return ((trip)(results[0]));
        }
        
        /// <remarks/>
        public void findByIdAsync(long arg0, bool arg0Specified) {
            this.findByIdAsync(arg0, arg0Specified, null);
        }
        
        /// <remarks/>
        public void findByIdAsync(long arg0, bool arg0Specified, object userState) {
            if ((this.findByIdOperationCompleted == null)) {
                this.findByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByIdOperationCompleted);
            }
            this.InvokeAsync("findById", new object[] {
                        arg0,
                        arg0Specified}, this.findByIdOperationCompleted, userState);
        }
        
        private void OnfindByIdOperationCompleted(object arg) {
            if ((this.findByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findByIdCompleted(this, new findByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trip[] findByPromoterAndOpen([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("findByPromoterAndOpen", new object[] {
                        arg0});
            return ((trip[])(results[0]));
        }
        
        /// <remarks/>
        public void findByPromoterAndOpenAsync(string arg0) {
            this.findByPromoterAndOpenAsync(arg0, null);
        }
        
        /// <remarks/>
        public void findByPromoterAndOpenAsync(string arg0, object userState) {
            if ((this.findByPromoterAndOpenOperationCompleted == null)) {
                this.findByPromoterAndOpenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByPromoterAndOpenOperationCompleted);
            }
            this.InvokeAsync("findByPromoterAndOpen", new object[] {
                        arg0}, this.findByPromoterAndOpenOperationCompleted, userState);
        }
        
        private void OnfindByPromoterAndOpenOperationCompleted(object arg) {
            if ((this.findByPromoterAndOpenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findByPromoterAndOpenCompleted(this, new findByPromoterAndOpenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trip registerTrip([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trip arg0) {
            object[] results = this.Invoke("registerTrip", new object[] {
                        arg0});
            return ((trip)(results[0]));
        }
        
        /// <remarks/>
        public void registerTripAsync(trip arg0) {
            this.registerTripAsync(arg0, null);
        }
        
        /// <remarks/>
        public void registerTripAsync(trip arg0, object userState) {
            if ((this.registerTripOperationCompleted == null)) {
                this.registerTripOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterTripOperationCompleted);
            }
            this.InvokeAsync("registerTrip", new object[] {
                        arg0}, this.registerTripOperationCompleted, userState);
        }
        
        private void OnregisterTripOperationCompleted(object arg) {
            if ((this.registerTripCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerTripCompleted(this, new registerTripCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trip[] getAvailableTrips() {
            object[] results = this.Invoke("getAvailableTrips", new object[0]);
            return ((trip[])(results[0]));
        }
        
        /// <remarks/>
        public void getAvailableTripsAsync() {
            this.getAvailableTripsAsync(null);
        }
        
        /// <remarks/>
        public void getAvailableTripsAsync(object userState) {
            if ((this.getAvailableTripsOperationCompleted == null)) {
                this.getAvailableTripsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAvailableTripsOperationCompleted);
            }
            this.InvokeAsync("getAvailableTrips", new object[0], this.getAvailableTripsOperationCompleted, userState);
        }
        
        private void OngetAvailableTripsOperationCompleted(object arg) {
            if ((this.getAvailableTripsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAvailableTripsCompleted(this, new getAvailableTripsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trip[] viajesPendientes([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0) {
            object[] results = this.Invoke("viajesPendientes", new object[] {
                        arg0});
            return ((trip[])(results[0]));
        }
        
        /// <remarks/>
        public void viajesPendientesAsync(long arg0) {
            this.viajesPendientesAsync(arg0, null);
        }
        
        /// <remarks/>
        public void viajesPendientesAsync(long arg0, object userState) {
            if ((this.viajesPendientesOperationCompleted == null)) {
                this.viajesPendientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnviajesPendientesOperationCompleted);
            }
            this.InvokeAsync("viajesPendientes", new object[] {
                        arg0}, this.viajesPendientesOperationCompleted, userState);
        }
        
        private void OnviajesPendientesOperationCompleted(object arg) {
            if ((this.viajesPendientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.viajesPendientesCompleted(this, new viajesPendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trip[] findAllUserTrip([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
            object[] results = this.Invoke("findAllUserTrip", new object[] {
                        arg0,
                        arg0Specified});
            return ((trip[])(results[0]));
        }
        
        /// <remarks/>
        public void findAllUserTripAsync(long arg0, bool arg0Specified) {
            this.findAllUserTripAsync(arg0, arg0Specified, null);
        }
        
        /// <remarks/>
        public void findAllUserTripAsync(long arg0, bool arg0Specified, object userState) {
            if ((this.findAllUserTripOperationCompleted == null)) {
                this.findAllUserTripOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAllUserTripOperationCompleted);
            }
            this.InvokeAsync("findAllUserTrip", new object[] {
                        arg0,
                        arg0Specified}, this.findAllUserTripOperationCompleted, userState);
        }
        
        private void OnfindAllUserTripOperationCompleted(object arg) {
            if ((this.findAllUserTripCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findAllUserTripCompleted(this, new findAllUserTripCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trip[] findToClose() {
            object[] results = this.Invoke("findToClose", new object[0]);
            return ((trip[])(results[0]));
        }
        
        /// <remarks/>
        public void findToCloseAsync() {
            this.findToCloseAsync(null);
        }
        
        /// <remarks/>
        public void findToCloseAsync(object userState) {
            if ((this.findToCloseOperationCompleted == null)) {
                this.findToCloseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindToCloseOperationCompleted);
            }
            this.InvokeAsync("findToClose", new object[0], this.findToCloseOperationCompleted, userState);
        }
        
        private void OnfindToCloseOperationCompleted(object arg) {
            if ((this.findToCloseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findToCloseCompleted(this, new findToCloseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trip[] findByPromoter([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
            object[] results = this.Invoke("findByPromoter", new object[] {
                        arg0,
                        arg0Specified});
            return ((trip[])(results[0]));
        }
        
        /// <remarks/>
        public void findByPromoterAsync(long arg0, bool arg0Specified) {
            this.findByPromoterAsync(arg0, arg0Specified, null);
        }
        
        /// <remarks/>
        public void findByPromoterAsync(long arg0, bool arg0Specified, object userState) {
            if ((this.findByPromoterOperationCompleted == null)) {
                this.findByPromoterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByPromoterOperationCompleted);
            }
            this.InvokeAsync("findByPromoter", new object[] {
                        arg0,
                        arg0Specified}, this.findByPromoterOperationCompleted, userState);
        }
        
        private void OnfindByPromoterOperationCompleted(object arg) {
            if ((this.findByPromoterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findByPromoterCompleted(this, new findByPromoterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void update([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trip arg0) {
            this.Invoke("update", new object[] {
                        arg0});
        }
        
        /// <remarks/>
        public void updateAsync(trip arg0) {
            this.updateAsync(arg0, null);
        }
        
        /// <remarks/>
        public void updateAsync(trip arg0, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        arg0}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
    public partial class listadoDTO {
        
        private trip[] viajesField;
        
        private trip[] viajesPromoterField;
        
        private trip[] viajesSeatField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("viajes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trip[] viajes {
            get {
                return this.viajesField;
            }
            set {
                this.viajesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("viajesPromoter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trip[] viajesPromoter {
            get {
                return this.viajesPromoterField;
            }
            set {
                this.viajesPromoterField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("viajesSeat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trip[] viajesSeat {
            get {
                return this.viajesSeatField;
            }
            set {
                this.viajesSeatField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
    public partial class trip {
        
        private System.DateTime arrivalDateField;
        
        private bool arrivalDateFieldSpecified;
        
        private int availablePaxField;
        
        private bool availablePaxFieldSpecified;
        
        private System.DateTime closingDateField;
        
        private bool closingDateFieldSpecified;
        
        private string commentsField;
        
        private addressPoint departureField;
        
        private System.DateTime departureDateField;
        
        private bool departureDateFieldSpecified;
        
        private addressPoint destinationField;
        
        private double estimatedCostField;
        
        private bool estimatedCostFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private int maxPaxField;
        
        private bool maxPaxFieldSpecified;
        
        private long promoterIdField;
        
        private bool promoterIdFieldSpecified;
        
        private tripStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string tripStatusField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                this.arrivalDateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arrivalDateSpecified {
            get {
                return this.arrivalDateFieldSpecified;
            }
            set {
                this.arrivalDateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int availablePax {
            get {
                return this.availablePaxField;
            }
            set {
                this.availablePaxField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool availablePaxSpecified {
            get {
                return this.availablePaxFieldSpecified;
            }
            set {
                this.availablePaxFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime closingDate {
            get {
                return this.closingDateField;
            }
            set {
                this.closingDateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool closingDateSpecified {
            get {
                return this.closingDateFieldSpecified;
            }
            set {
                this.closingDateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public addressPoint departure {
            get {
                return this.departureField;
            }
            set {
                this.departureField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime departureDate {
            get {
                return this.departureDateField;
            }
            set {
                this.departureDateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool departureDateSpecified {
            get {
                return this.departureDateFieldSpecified;
            }
            set {
                this.departureDateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public addressPoint destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double estimatedCost {
            get {
                return this.estimatedCostField;
            }
            set {
                this.estimatedCostField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estimatedCostSpecified {
            get {
                return this.estimatedCostFieldSpecified;
            }
            set {
                this.estimatedCostFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxPax {
            get {
                return this.maxPaxField;
            }
            set {
                this.maxPaxField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxPaxSpecified {
            get {
                return this.maxPaxFieldSpecified;
            }
            set {
                this.maxPaxFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long promoterId {
            get {
                return this.promoterIdField;
            }
            set {
                this.promoterIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool promoterIdSpecified {
            get {
                return this.promoterIdFieldSpecified;
            }
            set {
                this.promoterIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tripStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tripStatus {
            get {
                return this.tripStatusField;
            }
            set {
                this.tripStatusField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
    public partial class addressPoint {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
    public enum tripStatus {
        
        /// <comentarios/>
        OPEN,
        
        /// <comentarios/>
        CLOSED,
        
        /// <comentarios/>
        CANCELLED,
        
        /// <comentarios/>
        DONE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void findPromoterOrParticipatedCompletedEventHandler(object sender, findPromoterOrParticipatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findPromoterOrParticipatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findPromoterOrParticipatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public listadoDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((listadoDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void findByIdCompletedEventHandler(object sender, findByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public trip Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((trip)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void findByPromoterAndOpenCompletedEventHandler(object sender, findByPromoterAndOpenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findByPromoterAndOpenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findByPromoterAndOpenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public trip[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((trip[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void registerTripCompletedEventHandler(object sender, registerTripCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registerTripCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registerTripCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public trip Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((trip)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getAvailableTripsCompletedEventHandler(object sender, getAvailableTripsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAvailableTripsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAvailableTripsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public trip[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((trip[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void viajesPendientesCompletedEventHandler(object sender, viajesPendientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class viajesPendientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal viajesPendientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public trip[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((trip[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void findAllUserTripCompletedEventHandler(object sender, findAllUserTripCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findAllUserTripCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findAllUserTripCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public trip[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((trip[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void findToCloseCompletedEventHandler(object sender, findToCloseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findToCloseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findToCloseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public trip[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((trip[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void findByPromoterCompletedEventHandler(object sender, findByPromoterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findByPromoterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findByPromoterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public trip[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((trip[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void updateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591