//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace sdi3_10.Cli_SOAP_CSharp.RatingsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EjbRatingsServiceServiceSoapBinding", Namespace="http://impl.business.sdi.com/")]
    public partial class EjbRatingsServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback findAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeOperationCompleted;
        
        private System.Threading.SendOrPostCallback findByLastMonthOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EjbRatingsServiceService() {
            this.Url = global::sdi3_10.Cli_SOAP_CSharp.Properties.Settings.Default.sdi3_10_Cli_SOAP_CSharp_RatingsService_EjbRatingsServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event findAllCompletedEventHandler findAllCompleted;
        
        /// <remarks/>
        public event removeCompletedEventHandler removeCompleted;
        
        /// <remarks/>
        public event findByLastMonthCompletedEventHandler findByLastMonthCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rating[] findAll() {
            object[] results = this.Invoke("findAll", new object[0]);
            return ((rating[])(results[0]));
        }
        
        /// <remarks/>
        public void findAllAsync() {
            this.findAllAsync(null);
        }
        
        /// <remarks/>
        public void findAllAsync(object userState) {
            if ((this.findAllOperationCompleted == null)) {
                this.findAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAllOperationCompleted);
            }
            this.InvokeAsync("findAll", new object[0], this.findAllOperationCompleted, userState);
        }
        
        private void OnfindAllOperationCompleted(object arg) {
            if ((this.findAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findAllCompleted(this, new findAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void remove([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
            this.Invoke("remove", new object[] {
                        arg0,
                        arg0Specified});
        }
        
        /// <remarks/>
        public void removeAsync(long arg0, bool arg0Specified) {
            this.removeAsync(arg0, arg0Specified, null);
        }
        
        /// <remarks/>
        public void removeAsync(long arg0, bool arg0Specified, object userState) {
            if ((this.removeOperationCompleted == null)) {
                this.removeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveOperationCompleted);
            }
            this.InvokeAsync("remove", new object[] {
                        arg0,
                        arg0Specified}, this.removeOperationCompleted, userState);
        }
        
        private void OnremoveOperationCompleted(object arg) {
            if ((this.removeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rating[] findByLastMonth() {
            object[] results = this.Invoke("findByLastMonth", new object[0]);
            return ((rating[])(results[0]));
        }
        
        /// <remarks/>
        public void findByLastMonthAsync() {
            this.findByLastMonthAsync(null);
        }
        
        /// <remarks/>
        public void findByLastMonthAsync(object userState) {
            if ((this.findByLastMonthOperationCompleted == null)) {
                this.findByLastMonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByLastMonthOperationCompleted);
            }
            this.InvokeAsync("findByLastMonth", new object[0], this.findByLastMonthOperationCompleted, userState);
        }
        
        private void OnfindByLastMonthOperationCompleted(object arg) {
            if ((this.findByLastMonthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findByLastMonthCompleted(this, new findByLastMonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
    public partial class rating {
        
        private string commentField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private long seatAboutTripIdField;
        
        private bool seatAboutTripIdFieldSpecified;
        
        private long seatAboutUserIdField;
        
        private bool seatAboutUserIdFieldSpecified;
        
        private long seatFromTripIdField;
        
        private bool seatFromTripIdFieldSpecified;
        
        private long seatFromUserIdField;
        
        private bool seatFromUserIdFieldSpecified;
        
        private int valueField;
        
        private bool valueFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long seatAboutTripId {
            get {
                return this.seatAboutTripIdField;
            }
            set {
                this.seatAboutTripIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool seatAboutTripIdSpecified {
            get {
                return this.seatAboutTripIdFieldSpecified;
            }
            set {
                this.seatAboutTripIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long seatAboutUserId {
            get {
                return this.seatAboutUserIdField;
            }
            set {
                this.seatAboutUserIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool seatAboutUserIdSpecified {
            get {
                return this.seatAboutUserIdFieldSpecified;
            }
            set {
                this.seatAboutUserIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long seatFromTripId {
            get {
                return this.seatFromTripIdField;
            }
            set {
                this.seatFromTripIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool seatFromTripIdSpecified {
            get {
                return this.seatFromTripIdFieldSpecified;
            }
            set {
                this.seatFromTripIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long seatFromUserId {
            get {
                return this.seatFromUserIdField;
            }
            set {
                this.seatFromUserIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool seatFromUserIdSpecified {
            get {
                return this.seatFromUserIdFieldSpecified;
            }
            set {
                this.seatFromUserIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void findAllCompletedEventHandler(object sender, findAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public rating[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((rating[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void removeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void findByLastMonthCompletedEventHandler(object sender, findByLastMonthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findByLastMonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findByLastMonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public rating[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((rating[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591